### ISSUE TITLE
Start up the group

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/admin#1]
What we need: 

 * [x] [Write blog post](https://etherpad.mozilla.org/incubatorcg). 
 * [x] Create the actual CG? 
 * [x] Coordinate with RICG. 
 * [x] Decide on IRC/Slack? channel? 
 * [x] Publish blog post
 * [x] Getting a site (http://wicg.io) up in place 
 * [x] Get an IRC logger working

**Comment by yoavweiss** [comment]
Regarding IRC/Slack - Slack certainly seems to be where all the cool kids are nowadays.
The main problem I see with it is logging, but that may be resolved by hooking up an IRC bot to its [IRC interface](https://slack.zendesk.com/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP).

**Comment by yoavweiss** [comment]
Other tasks would be:
* Getting a site up in place (I bought wicg.io :dancer:)
* Get an IRC logger working

**Comment by marcoscaceres** [comment]
I added the two you listed above... though they might be better as separate bugs.

**Comment by jonathanKingston** [comment]
@yoavweiss can I suggest gitter and telegram as free alternatives without limitations on messages, both are equally as accessible as slack. Neither have the 10k chat limit which happens sooner than people expect.

**Comment by marcoscaceres** [comment]
We should probably wait till we have project set up and people involved. Preferred communication channels will likely be dictated by whomever is leading a project. It doesn't hurt to be prepared nonetheless, but we shouldn't be too presumptuous.

**Comment by marcoscaceres** [comment]
Ok, sent link to the post to @wilto. Once we get a :+1: from him, we can publish.

**Comment by Wilto** [comment]
Thumbs-up; consider the WICG and RICG somewhat more coordinated. I’m working up a quick blog post  from the RICG side of things now.

**Comment by marcoscaceres** [comment]
Thanks @Wilto. [Published](http://www.w3.org/blog/2015/07/wicg/). Really liked your Extensible Web post, btw!

**Comment by Wilto** [comment]
Early draft, but I want to run this by all of you. Direct edits welcome.
https://etherpad.mozilla.org/ricg-wicg

+@cwilso

**Comment by marcoscaceres** [comment]
:heart: it!

**Comment by marcoscaceres** [comment]
:joy: launch achieved.
