### ISSUE TITLE
Charter claims to have never been modified

### ISSUE THREAD

**Issue by hober** [WICG/admin#103]
At the very top of the charter, it says this:

* Start Date: 2 July 2015
* Last Modified: 2 July 2015

But it's clear from [charter.html's revision history](https://github.com/WICG/admin/commits/gh-pages/charter.html) that the charter has changed a number of times since then.

Minimally, the "Last Modified" line should be updated when the charter is changed. Ideally, the charter would include links to all previous versions.

**Comment by marcoscaceres** [comment]
Thanks @hober for spotting that! Dynamically updated the last modified, plus added link to commit history.
