### ISSUE TITLE
Archiving ResizeObserver

### ISSUE THREAD

**Issue by takenspc** [WICG/admin#106]
ResizeObserver spec has moved to CSSWG so that new issues should not be filed in WICG.

https://github.com/WICG/ResizeObserver

However the project is still listed at <https://wicg.io/>.

If the project was archived, new issues can't be filed in it and [https://wicg.io/ won't display it](https://github.com/WICG/wicg.io/blob/gh-pages/generator.js#L53).

I think it is time to archive the project.

**Comment by trusktr** [comment]
Slightly off topic, but I'm a little confused: why is there both http://github.com/WICG and http://github.com/w3c? Why don't we have just one GitHub org for all web proposals and not worry about archiving/moving? Is one org for official specs, the other for proposals?

Edit: Oh, there's also https://github.com/whatwg, another place for spec stuff. Can we have only place?

**Comment by marcoscaceres** [comment]
@astearns, @atanassov, could we kindly ask that the CSS WG please follow the process when adopting specs (i.e., so we know ahead of time what things are being adopted and we can shut down repos at the same time). Please see https://github.com/WICG/admin/blob/gh-pages/intent-to-migrate.md

**Comment by marcoscaceres** [comment]
Disabled Github pages + added redirect to https://github.com/WICG/wicg.github.io

**Comment by astearns** [comment]
(looking at the admin docs) @marcoscaceres am I correct that the process is to have the WIGC editors work with the WICG chairs to do an intent to migrate? Is there anything else you’d like us to do?

**Comment by marcoscaceres** [comment]
@astearns nope, that's it :) We are here to help and to make any the transitions as smooth/quick as possible... it's just so we can tick boxes, update links, etc.
