### ISSUE TITLE
Archiving scroll-animations

### ISSUE THREAD

**Issue by takenspc** [WICG/admin#107]
The scroll-animations spec has moved to CSSWG so that new issues should not be filed in WICG.

https://wicg.github.io/scroll-animations/

However WICG's project is still listed at <https://wicg.io/>.

Once the project is archived, new issues can't be filed in it and [https://wicg.io/ won't display it](https://github.com/WICG/wicg.io/blob/gh-pages/generator.js#L53).

I think it is time to archive the project.

Also,

- The spec page should redirect users to the new spec page.

    https://wicg.github.io/scroll-animations/

    https://drafts.csswg.org/scroll-animations-1/

- The biblio.json may be need to updated.

    https://github.com/WICG/admin/blob/gh-pages/biblio.json

Note: I'm a fun of both ResizeObserver and scroll-animations and appreciate all of inculbation works.

**Comment by marcoscaceres** [comment]
Checked biblio - all good there.

**Comment by yoavweiss** [comment]
Archived! Thanks for flagging this :)

**Comment by marcoscaceres** [comment]
Disabled Github pages + added redirect to https://github.com/WICG/wicg.github.io

**Comment by takenspc** [comment]
I appreciate you managing the incubation group in these tough times.  :joy:
