### ISSUE TITLE
How do we get involved or express support?

### ISSUE THREAD

**Issue by computersarecool** [WICG/admin#108]
Many of the new APIs, such as Web Serial, say: 

> It is not a W3C Standard nor is it on the W3C Standards Track. 

I am wondering how someone can get involved to express support or join in the effort to get standards like this on the standards track?

I have joined the WICG but I am not sure what else to do from there.  I would appreciate input on this.

Thanks

**Comment by marcoscaceres** [comment]
Hi @computersarecool (heh, they sure are!)

> I am wondering how someone can get involved to express support or join in the effort to get standards like this on the standards track?

So, it's so much a not a matter of expressing support, but a matter of implementer and working group interest in taking on the work. To progress things to the W3C, we require an incubation to fill out this form:    
https://github.com/WICG/admin/blob/gh-pages/intent-to-migrate.md 

For more details, see step 4 here:
https://github.com/wicg/admin/#contributing-new-proposals

**Comment by computersarecool** [comment]
Cool. That makes sense. Thanks for sharing.  These are exciting things in development.

**Comment by marcoscaceres** [comment]
@computersarecool, is there some particular spec you'd like to get involved in? The best thing to do is read over the spec, and see if it makes sense or if you spot any issues... even if just typos, or bugs in examples - or if you have additional ideas you'd like to propose. If you do find anything, please file a bug on the appropriate spec. 

If you think that a spec is of good quality, and should be moved to the W3C "proper", then you can also file a bug on the spec to petition the spec Editors to move the spec into a Working Group (you can cc "@WICG/chairs" for support too, and we can help evaluate if something is ready to move into the W3C or not).

**Comment by computersarecool** [comment]
@marcoscaceres well I have been recently working a lot with the Web Serial API.  It is an example of an API that is now at least implemented (in Chrome) but the "not on a standards track" is a little worrisome because I have experience with spending time with APIs that were eventually deprecated. So I'd like to try to do what I can so that doesn't happen to these new specs which I find useful. Web Serial is a good one where there doesn't seem to be that much work that is needed.

**Comment by marcoscaceres** [comment]
> @marcoscaceres well I have been recently working a lot with the Web Serial API.

Ah, a spec close and dear to my heart. cc @reillyeon! 

> It is an example of an API that is now at least implemented (in Chrome) but the "not on a standards track" is a little worrisome because I have experience with spending time with APIs that were eventually deprecated. 

Yeah, that's a challenging one indeed... as the community hasn't gotten any feedback from WebKit or Mozilla. 

> So I'd like to try to do what I can so that doesn't happen to these new specs which I find useful. Web Serial is a good one where there doesn't seem to be that much work that is needed.

Ok, one active thing that is yet to be done is get a Mozilla position on that spec. Would you be willing to file a bug at the following place (it has a simple template to follow... you can ignore any optional things): 

https://github.com/mozilla/standards-positions/issues

That will at least give it some attention over on the Mozilla side... the WebKit folks also monitor that repo, so it's likely they will comment there too (or we can ping them to comment if need be).

**Comment by marcoscaceres** [comment]
Here is the related Mozilla bug from 7 years ago:
https://bugzilla.mozilla.org/show_bug.cgi?id=webserial

Seems someone even wrote a small patch... though I doubt it matches the spec anymore.

**Comment by computersarecool** [comment]
Sure will do.  In case anyone else is reading this I believe that hyperlink is missing an `s` and should be: https://github.com/mozilla/standards-positions/issues

**Comment by computersarecool** [comment]
@marcoscaceres also are you a: "Mozillan that can provide input"

Also, going forward, is there a way to figure out what can be done to help without messaging you directly?

**Comment by marcoscaceres** [comment]
> @marcoscaceres also are you a: "Mozillan that can provide input"

Yep, I can be that person...thank for filling the bug. 

> Also, going forward, is there a way to figure out what can be done to help without messaging you directly?

@reillyeon can probably provide you with some guidance of how you can be involved... I'd suggest speaking to him directly or jumping straight into the existing bugs... or file a bug over in Serial API repo asking "how can I help?".

**Comment by computersarecool** [comment]
Awesome.  Well thanks for all of this.  Hoping more of these new / providing native access type APIs get approved and standardized.
