### ISSUE TITLE
New repo + collaborator request

### ISSUE THREAD

**Issue by LuHuangMSFT** [WICG/admin#113]
Hello Chairs. I would like to request that we start a new repo to incubate this proposal:
https://discourse.wicg.io/t/proposal-pwas-as-uri-handlers/4394

😊

**Comment by travisleithead** [comment]
[Chair hat on] According to https://discourse.wicg.io/t/proposal-pwas-as-uri-handlers/4394/7 you've got clear signal from others of interest in this proposal, and sounds like we should get this process started!

**Comment by travisleithead** [comment]
Repo is active at: https://github.com/WICG/pwa-url-handler
