### ISSUE TITLE
Intent to migrate WebTransport to a newly-formed WG

### ISSUE THREAD

**Issue by vasilvv** [WICG/admin#119]
### Working group decision to adopt

If the group is formed, it would be incorporated through the charter: https://w3c.github.io/webtransport-charter/charter.html

### Proposal

https://github.com/wicg/web-transport

### Summary

WebTransport is an API that allows web applications to establish interactive, bidirectional, multiplexed network connections to a remote server.

### Motivation and Use Cases

Detailed in the [explainer](https://github.com/WICG/web-transport/blob/master/explainer.md).

### Compatibility Risk

It's a new JavaScript API, meaning that if we remove it, websites relying on it would break.  It does not have any other compatibility risks that differ from similar APIs.

### Ongoing technical constraints

What technical constraints will be added to user agents implementing this feature?

None.

Will this feature be supported in all environments (desktop, mobile, tablets, TV, eBooks, automotive, etc.)?

Yes.

### Link to implementation experience and demos

Chrome has implemented QuicTransport, and is experimenting with it as an origin trial: https://web.dev/quictransport/

### Data

According to Chrome UseCounters, 9.3% of all web page loads use WebSocket.  That would be a good approximation on the upper bound of web pages that could benefit from this, as WebTransport is functionally a superset of WebSocket.

### Security and Privacy

Discussed in https://wicg.github.io/web-transport/#privacy-security

### Accessibility

No accessibility implications.

### Internationalization

No i18n implication.  All of the data path APIs only accept binary input.

**Comment by marcoscaceres** [comment]
Thanks for putting this together @vasilvv! I guess you will let us know when the new group is up and running.

**Comment by cwilso** [comment]
Has migrated.
