### ISSUE TITLE
Hypothetical: what if we moved from Discourse to Github

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/admin#120]
@yoavweiss mentioned that it might be worth exploring moving from Discourse to GitHub... what would be some of the pros/cons of that?

**Comment by travisleithead** [comment]
Pro: more consistent process
Pro: only one account/login needed (for GitHub) to discuss new ideas and then transition to work on them.

Equivalent: both have systems for categorization, notification/tracking, threaded discussions.

Con: lots of content on discourse already--how would we advise in-progress conversations to move?

Also note, it doesn't have to be a "move"--we can start up the GitHub process in-parallel, and run both for a time to see how it goes (though we probably do want to have a single process in the long-run).

**Comment by hober** [comment]
Pro: people can track new ideas the exact same way they track issues raised on ideas that have graduated from discourse to GitHub

The Privacy CG uses GitHub in much the same way WICG uses Discourse; we have a `proposals` repo for this: https://github.com/privacycg/proposals/issues
So far I think that's working well for us.

(And personally, I'm far more likely to regularly follow such a process on GitHub. I very rarely look at WICG's discourse.)

**Comment by Crissov** [comment]
Users can already sign and log in to Discourse with their Github credentials, so they really only need a single “account” if they want.

There are some Discourse plug-ins that could improve the integration of topics and repos, issues or pull requests, e. g. [Discourse Code Review](https://meta.discourse.org/t/discourse-code-review/103142) and [Discourse Github](https://meta.discourse.org/t/discourse-github/99895).

Discourse is better for actual open discussion. The only thing missing is being able to pull in experts and stakeholders by at-mentioning them if they are only active on another platform, e. g. Github.

**Comment by sideshowbarker** [comment]
> (And personally, I'm far more likely to regularly follow such a process on GitHub. I very rarely look at WICG's discourse.)

Same here. And same in general for discourse instances for other work I’m involved in or follow — I just never seem to get around to taking the time to check any related discourse discussions. And that’s not because I have anything against discourse as a tool — it’s just that I’ve never managed to keep up to date with it or integrate it into my personal workflow.

So my own experience pretty strongly suggests to me that if we were to consolidate WICG work discussions into WICG GitHub, that’s gonna integrate better with a lot of people’s personal workflows — and so, I think, result in a higher level of engagement in WICG discussions, from a broader set of people.

**Comment by Crissov** [comment]
Still, you could lose valuable input from some people who for some reason or another either avoid that techy, nerdy, scary place called Github or are excluded from participation, e.g. due to US sanctions.

**Comment by hober** [comment]
I assume this is the intent of [WICG/proposals](https://github.com/WICG/proposals)?

**Comment by yoavweiss** [comment]
Indeed

**Comment by travisleithead** [comment]
Agree, a lot of our discussions (especially for new proposals) have transferred to WICG/proposals.

Note, we do need to update some of the docs to reflect this still (see https://github.com/WICG/admin/issues/133)
