### ISSUE TITLE
Archive kv-storage?

### ISSUE THREAD

**Issue by dontcallmedom** [WICG/admin#121]
[KV Storage](https://wicg.github.io/kv-storage/) says work on it is suspended - I wonder if the repo should be archived to reflect that.

I don't have an issue if the intent is to keep it open to allow new interest to be manifested there if that seems like a likely future.

**Comment by marcoscaceres** [comment]
Thanks for letting us know. Yes, we should archive it. Will do that when the @wicg/chairs next meet (unless someone beats me to it!).

**Comment by yoavweiss** [comment]
The spec seems to have a bunch of open issues. Should we archive while keeping them open?

/cc @domenic

**Comment by domenic** [comment]
Is that possible? I thought GitHub closed the issue tracker and prevented further discussion on archived repos.

**Comment by yoavweiss** [comment]
We can keep them open, but discussions would indeed be prevented if we archive.
The alternative is to close them all, or not to archive if the discussions are still somewhat ongoing.

**Comment by marcoscaceres** [comment]
Personally, I don't think it makes sense to close the issues arbitrarily - I'd rather we archive and just capture the state of the work at the time it was archived... "snap frozen" :)

**Comment by domenic** [comment]
I'm going to fully archive it and try to remove it from the relevant databases.
