### ISSUE TITLE
TPAC Sessions

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/admin#122]
Should we organize sessions for TPAC?

**Comment by reillyeon** [comment]
I would like to organize sessions for specifications I've been working on such as Idle Detection, Serial and WebUSB. Do we want to  organize sessions here first or have the participants in each incubation organize them for ourselves?

**Comment by yoavweiss** [comment]
@reillyeon - I sent out a [call for sessions](https://lists.w3.org/Archives/Public/public-wicg/2020Aug/0000.html) on the mailing list, after you posted this... :)
Can you add the sessions you want to run to https://www.w3.org/wiki/TPAC/2020/GroupMeetings#:~:text=Community%20Groups%20will%20be%20able%20to%20meet%20during%20the%20Fall%202020%20TPAC%20event.?

**Comment by yoavweiss** [comment]
@reillyeon - Added a joint session on all the above to https://www.w3.org/wiki/TPAC/2020/GroupMeetings#:~:text=Idle%20detection%2C%20Serial%2C%20WebUSB%20proposals

Let me know if that works

**Comment by reillyeon** [comment]
Thanks!
