### ISSUE TITLE
Set up hooks that post proposals to discourse

### ISSUE THREAD

**Issue by yoavweiss** [WICG/admin#125]
With the new proposals repo, and with the fact that we need to keep discourse around for non-proposal discussions as well as archiving purposes, it might be good to set up hooks so that issues on the proposals repo get posted to discourse automatically.
That would enable folks that mainly monitor discourse to keep track of proposals, and notify them of this work happening.

Thoughts?

**Comment by travisleithead** [comment]
Seems fine to me. :)

**Comment by yoavweiss** [comment]
With Discourse being archived, I think we can close this one.
