### ISSUE TITLE
Update links to CEPC

### ISSUE THREAD

**Issue by xfq** [WICG/admin#127]
Since the CEPC has been revised, many link fragments in https://github.com/WICG/admin#code-of-conduct are broken now.

**Comment by yoavweiss** [comment]
Wouldn't it be better to file this issue against the new CEPC, to ensure the maintain past links?
Surely this is not the only document that's using the old anchors?

**Comment by xfq** [comment]
Filed an issue here: https://github.com/w3c/PWETF/issues/149
