### ISSUE TITLE
Censorship of comments within the context of the charter

### ISSUE THREAD

**Issue by tkocou** [WICG/admin#129]
I read the charter for WICG. I do not see where it grants censorship to WICG for comments made in a particular GitHub branch. Please explain why the WICG group censors comments when they lack authority to do so.

**Comment by yoavweiss** [comment]
Not sure which specific incident you're referring to, but please see https://www.w3.org/Consortium/cepc/

**Comment by cwilso** [comment]
It would be useful to have more details.  In general: the chairs *DO* have authority, as Yoav pointed to, to ensure discussions are respectful.  I would also expect individual incubation editors to support the CEPC as well, including removing comments that do not adhere to the CEPC.  They should not be censoring comments for reasons of simple disagreement, however.

**Comment by tkocou** [comment]
It's ok. After doing some homework, I realize that I shouldn't have been
able to comment. In a nutshell, the thread should have been locked from
it's inception.

**Comment by tkocou** [comment]
closing comment
