### ISSUE TITLE
Rename "native-file-system" repo to "file-system-access"

### ISSUE THREAD

**Issue by mkruisselbrink** [WICG/admin#130]
In https://github.com/WICG/native-file-system/pull/227 we're updating the Native File System API to be called the File System Access API instead. The repo should probably be renamed at the same time as that PR lands.

I think I can just rename the repo myself, but I'm not sure if there are other places the name will need to be updated as well?

**Comment by yoavweiss** [comment]
https://github.com/search?q=org%3AWICG+native-file-system&type=code shows a few places

**Comment by mkruisselbrink** [comment]
I send out pull requests for wicg.io/repos.json and biblio.json in this repo. The references in https://github.com/WICG/wicg.github.io seem to be auto-generated from some other tracking thing?

**Comment by yoavweiss** [comment]
^^ @plehegar

**Comment by plehegar** [comment]
The references in wicg.github.io are generated from the [Google spreadsheet](https://docs.google.com/spreadsheets/d/1K2EtkvKXMDk_h2goR34uMIWmw1LfPhIi-QAJHcQBP_4/edit#gid=0).

**Comment by yoavweiss** [comment]
Modified the spreadsheet to refer to the new name

**Comment by plehegar** [comment]
B70 in the spreadsheet still has the old link.

**Comment by yoavweiss** [comment]
Actually fixed now...
