### ISSUE TITLE
WICG unofficial drafts are still considered as "open standard"

### ISSUE THREAD

**Issue by rniwa** [WICG/admin#132]
See https://twitter.com/simevidas/status/1314633006443888643

[Mark CG-Drafts as unofficial](https://github.com/w3c/tr-design/pull/177) has helped but we need to do more to make it clear that single vendor feature which gets published in WICG doesn't become an open standard by the virtue of its existence.

**Comment by travisleithead** [comment]
We think https://github.com/WICG/admin/issues/138 will also be quite helpful with this.

Ultimately we can't prevent folks from being confused, but aspire to help make our incubation states (and implementation status of each more clear).
