### ISSUE TITLE
Admin docs should point to proposals repo for new proposals

### ISSUE THREAD

**Issue by clelland** [WICG/admin#133]
README.md here suggests that new proposals should start out as a post on Discourse. I believe that, since https://discourse.wicg.io/t/introducing-a-new-home-for-proposals/4758, the process should be to file a new issue in the [proposals](https://github.com/WICG/proposals) repo instead.

The README file should be updated to describe the new process.

**Comment by travisleithead** [comment]
Thanks for the issue! This indeed has been on our TODO list for a while. @cwilso when you get the chance...

**Comment by yoavweiss** [comment]
I believe this was closed by #172 
Thanks @marcoscaceres !!

**Comment by aody9992o** [comment]
omgandtawan@gmail.com
