### ISSUE TITLE
Request to Adopt: stuartpb/wicg-best-practices

### ISSUE THREAD

**Issue by stuartpb** [WICG/admin#14]
(following the pattern suggested in #13)

Basically, this is a repo whose primary feature is its wiki, with pages like https://github.com/stuartpb/wicg-best-practices/wiki/WICG-Best-Practices that describe how to be effective in WICG.

This would be moved from https://github.com/stuartpb/wicg-best-practices to https://github.com/WICG/best-practices (or maybe WICG/wicg-best-practices to distinguish it from something like Technical Architecture Group best practices).

**Comment by yoavweiss** [comment]
Thanks! While the text is great, do we need it to be in its own repo? Do you see this text evolving?

Maybe it should be part of https://github.com/WICG/wicg.io instead?

**Comment by stuartpb** [comment]
Yes, I foresee this text evolving, with open contributions from other users on GitHub (hence the use of the wiki rather than files in the repo).

**Comment by stuartpb** [comment]
More than the text of that specific list of best practices, I see it being supplemented with other, more specific best practices like [best practices specifically around implementation](http://discourse.wicg.io/t/difficulty-ratings-for-proposals/975), as other pages on the wiki.

**Comment by marcoscaceres** [comment]
Closing as not actionable.
