### ISSUE TITLE
Mark frame-timing as depredated and archive repo

### ISSUE THREAD

**Issue by dontcallmedom** [WICG/admin#141]
I understand from https://github.com/w3c/browser-specs/pull/394 that [Frame Timing](https://wicg.github.io/frame-timing/) is no longer pursued; it would be good to get that reflected in the spec itself, the repo readme, and probably to archive the repo as a result.

**Comment by yoavweiss** [comment]
Done!

**Comment by yoavweiss** [comment]
Looking deeper, we'd also need to clarify that in the spec itself, not just in the README

**Comment by yoavweiss** [comment]
Now it's actually done.
