### ISSUE TITLE
is there a chatroom? if so, where?

### ISSUE THREAD

**Issue by npdoty** [WICG/admin#147]
Readme gives instructions for a Gitter room, but it seems like that isn't in use. Not clear if the IRC room (#wicg on irc.w3.org) linked from https://www.w3.org/community/wicg/ is in use, but if so, let's correct the link and instructions to point to that.

**Comment by yoavweiss** [comment]
I'm afraid there isn't currently an active chat room. Maybe we should create one on Matrix (as I'm no longer on IRC and not sure what's the status with Gitter is).

@cwilso @travisleithead @LJWatson - thoughts?

**Comment by cwilso** [comment]
Well, we do have a #WICG channel on the W3C Community Slack, but there's no traffic.  (But 43 participants!). 
W3C Community Slack: https://lists.w3.org/Archives/Public/public-web-and-tv/2020Mar/0028.html

**Comment by npdoty** [comment]
+1 for Matrix, and I think the gitter room could provide that (if an admin logs in and approves it maybe? I think Gitter has moved most rooms to Matrix). But mostly it seems like we need one place to be chosen so that we direct people to the right spot.

**Comment by cwilso** [comment]
We discussed, and decided to stick with the Slack as the community chatroom for now.

**Comment by npdoty** [comment]
Can you update the documentation so that people are pointed to the Slack channel rather than to other chatrooms that aren't being used?

These links (at least) have contradictory information:
https://www.w3.org/community/wicg/
https://github.com/WICG/admin/blob/gh-pages/README.md
