### ISSUE TITLE
A unique identifier for W3C specifications

### ISSUE THREAD

**Issue by kael** [WICG/admin#154]
It'd be nice if the W3C specifications had a unique ID that we could use to query APIs similarly to what is done with other standardization instances specifications.

[IETF Internet-Drafts & RFC](https://datatracker.ietf.org/doc/html/rfc2648) have an ID in the form of `urn:ietf:id:draft-blank-ietf-bimi-02` and `urn:ietf:rfc:9114`, and can be used with the [IETF API](https://datatracker.ietf.org/api/).

Similarly, there exists the same for [ETSI specifications](https://datatracker.ietf.org/doc/html/rfc2648), e.g `urn:etsi:102818` and [XSF specifications](https://datatracker.ietf.org/doc/html/rfc4854) (with spec versioning) e.g `urn:xmpp:feature-fallback:0`.

**Comment by jackromo888** [comment]
https://github.com/WICG/admin/issues/154#issue-1344161655

**Comment by cwilso** [comment]
Somewhat related to #138, and also to the general theme of "Incubation, Implementation, and Interoperability."

**Comment by kael** [comment]
As an addendum, each RFC ID has also a corresponding DOI as defined by [RFC 7669](https://dx.doi.org/10.17487/rfc7669).

**Comment by marcoscaceres** [comment]
I think this is outside the scope of the WICG, tbh... but would be something more general for the W3C. 

At the same time, I'm sure where to move this issue to, but it's probably not something we can tackle in the WICG.

@cwilso, maybe something for the AB as it's organization wide?

**Comment by marcoscaceres** [comment]
I'm included to close this as it's not a WICG issue... 

@dontcallmedom maybe you can suggest where this discussion should move to?

**Comment by dontcallmedom** [comment]
At least for Technical reports, I think the unique ID is the "This version" URI, which in particular can be used with the [W3C API](https://w3c.github.io/w3c-api/) to retrieve information about a specific version of a spec. But this approach doesn't apply to Community Groups (such as the WICG).

@kael I'm not sure if your request is about unique identifiers for specific versions of WICG documents, for Community Groups documents more generally, or if the "This Version" URI of W3C technical reports (see also ow [W3C manages spec versions](https://www.w3.org/2005/05/tr-versions) ) doesn't fulfil the requirements you had in mind.

**Comment by kael** [comment]
> I'm not sure if your request is about unique identifiers for specific versions of WICG documents, for Community Groups documents more generally, or if the "This Version" URI of W3C technical reports

I was thinking more about using CURIE - an URN - for W3C specifications ID as there are for IETF, ETSI or ISO specifications.

Looking at the [WebConcept specs](https://webconcepts.info/specs.json) list, it uses the W3C spec URL as its URI, whereas IETF or OASIS specs have an URN as an URI.

Versioning would be interesting, ISO URN handles versioning (IIRC).

The main request is about having a CURIE, URN-style, for W3C specifications, though - perhaps the issue should re-titled.

As an aside, making the W3C API opened the IETF way would be neat.

Cheers.
