### ISSUE TITLE
Should we close proposals when they are marked "repo-adopted"

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/admin#177]
For [repos that have been adopted](https://github.com/WICG/proposals/issues?q=is%3Aissue+is%3Aopen+label%3Arepo_adopted), should we close those issues? Having a smaller list of open issues might make the proposals list more manageable. 

I'm also ok to just leave them open. 

As for the process, we should always make sure that we include a link to where the repo ended up.

**Comment by yoavweiss** [comment]
The original intent waas to keep proposals open until they graduated, and mark them with the label. I think we haven't done a good job of actually doing that though (as some were closed, while other weren't).

It might be a good idea to just close them, and figure out a different way to keep tabs of all proposals in their various states.

**Comment by marcoscaceres** [comment]
My preference would be to close them, just to make the list more manageable.

**Comment by yoavweiss** [comment]
Done!
