### ISSUE TITLE
Add `djmitche` as org member

### ISSUE THREAD

**Issue by djmitche** [WICG/admin#179]
Hi! I'd like to be able to configure GitHub notification routing for issues in this organization, and [GitHub only allows that for org members](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#customizing-email-routes-per-organization).

I am already a member of the WI community group. If possible, could I be added as an org member?

**Comment by marcoscaceres** [comment]
Invite sent!
