### ISSUE TITLE
Update discourse FAQ to match WICG COC 

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/admin#18]

**Comment by stuartpb** [comment]
I actually think the Discourse Guidelines (the "FAQ") should remain as-is (if anything, they should be worked into the general WICG Best Practices corpus, which could be presented alongside them). The [Terms of Service](http://discourse.wicg.io/tos), however, don't make sense in their out-of-the-box form and need to be overhauled (they state that contributions are made under the terms of the CC-BY-NC-SA 3.0 license and not [the W3C CG CLA](https://www.w3.org/community/about/agreements/cla/), contain clauses relating to [payment](http://discourse.wicg.io/tos#4), and still contain several references to "Specifiction").
