### ISSUE TITLE
How to request wicg-discourse account anonymization?

### ISSUE THREAD

**Issue by ghost** [WICG/admin#180]
Hello all, can you all help me?

I would like to make my profile anonymous. It’s possible? What does it take to do this?

why?
- I spoke here about leaving the profile anonymous, because how the Discourse will be closed, and made publicly available. I thought about deactivating my profile so that I can remain anonymous.
- I would like to have the right to be forgotten.
- 'The "right to be forgotten" is a common name for a right that was first established in May 2014 in the European Union as the result of a [ruling](http://curia.europa.eu/juris/document/document.jsf?text=&docid=163494&pageIndex=0&doclang=EN&mode=req&dir=&occ=first&part=1&cid=10850128) by the European Court of Justice. The Court found that European data protection law gives individuals the right to ask search engines like Google to delist certain results for queries related to a person’s name.'
- I tried to reach the wicg community but got no response. Please, see this: [How can I change my username?](https://discourse.wicg.io/t/how-can-i-change-my-username/6164), [How can I make my account public and anonymous here?](https://discourse.wicg.io/t/how-can-i-make-my-account-public-and-anonymous-here/6161)

**Comment by yoavweiss** [comment]
> * I spoke here about leaving the profile anonymous, because how the Discourse will be closed, and made publicly available

Discourse was always a public forum. Making it read-only will not change that fact.



> * 'The "right to be forgotten" is a common name for a right that was first established in May 2014 in the European Union as the result of a [ruling](http://curia.europa.eu/juris/document/document.jsf?text=&docid=163494&pageIndex=0&doclang=EN&mode=req&dir=&occ=first&part=1&cid=10850128) by the European Court of Justice. The Court found that European data protection law gives individuals the right to ask search engines like Google to delist certain results for queries related to a person’s name.'
> * I tried to reach the wicg community but got no response. Please, see this: [How can I change my username?](https://discourse.wicg.io/t/how-can-i-change-my-username/6164), [How can I make my account public and anonymous here?](https://discourse.wicg.io/t/how-can-i-make-my-account-public-and-anonymous-here/6161)

I can delete any of your past comments, if that would address your concern. You can do so as well, as long the forum hasn't moved into read-only mode.

**Comment by ghost** [comment]
Hi yoavweiss, thank you for feedback here.

> Discourse was always a public forum. Making it read-only will not change that fact.

that is true.

> I can delete any of your past comments, if that would address your concern. 

If you can change my user profile name and turn off my access to wicg I would be happy. Could you change my profile name to a random name and remove my access?

> You can do so as well, as long the forum hasn't moved into read-only mode.

This is perhaps a problem.  I tried to remove this post but I couldn't: [[Spec] Import/Export passwords in Keepass format for all browsers](https://discourse.wicg.io/t/spec-import-export-passwords-in-keepass-format-for-all-browsers/5963).  For example, but no one moderated this post. I would like to remove it, because this post was a question and not a proposal.

**Comment by yoavweiss** [comment]
> If you can change my user profile name and turn off my access to wicg I would be happy. Could you change my profile name to a random name and remove my access?

Done!

**Comment by ghost** [comment]
Hi yoavweiss.

> Done!

thanks!
