### ISSUE TITLE
Meeting at TPAC?

### ISSUE THREAD

**Issue by LJWatson** [WICG/admin#181]
We have the opportunity to meet during [TPAC](https://www.w3.org/2023/09/TPAC/) (11 to 15 September).

If you would like a 45 minute slot at some point during the week to discuss your incubation, let us know (here) by the end of your day on Wednesday 10 May.

Slots will be limited so if you can include a short description of why you'd like to meet/what you'd like to discuss, that would be helpful.

Thanks /CC @yoavweiss, @marcoscaceres, @cwilso

**Comment by domfarolino** [comment]
@shivanigithub & I would like a session for [fenced frames](https://github.com/wicg/fenced-frame) to discuss future use case designs, as well as modifications to the current use cases.

**Comment by reillyeon** [comment]
@scheib and I would like a session on low-level device APIs. It would combine work currently incubating in the WICG (WebHID, WebUSB and Web Serial) along with Web NFC from the Web NFC CG and Web Bluetooth from the Web Bluetooth CG. Topics will vary depending on attendance but could include an overview of the current status of the APIs and adoption, discussion of current work on the specifications and implementation reports, and a triage of open issues.

Requested time: 1 hour

**Comment by reillyeon** [comment]
@b1tr0t and I would like a session on the Isolated Web Apps proposal, currently in incubation. Topics would include a report on implementation status and discussion of community feedback since the proposal was introduced last year.

Requested time: 1 hour

**Comment by michaelkleber** [comment]
I would like a session on the **Protected Audience API** (formerly known as FLEDGE), to report on the current implementation state in Chrome and ongoing work.  I'm still struggling with the ability to attend TPAC at all vs Rosh Hashanah starting on Friday, though.

[Edit to add: Please schedule this for Mon or Tues, not Fri]

**Requested duration: either 1hr or 90min**

**Comment by marcoscaceres** [comment]
Two sessions:

 * `ComputedAccessibleNode` (test-only interface or property bag) - https://github.com/WICG/aom/issues/197
 * General one on progressing Shape detection API, @yellowdoge, @reillyeon

**Comment by krgovind** [comment]
@johannhof @cfredric and I would like a session for First-Party Sets to discuss adoption/usability improvements for the API in advance of 3pc phase-out in Chrome, any new feature requests, etc.

**Comment by LJWatson** [comment]
Thanks everyone who has responded so far. We'll be putting the agenda together in the next week or so, so if there are any more meeting time requests, it'd be great if you could post them here ASAP. Thanks.

**Comment by mgiuca** [comment]
Hi @LJWatson and WICG chairs,

Not sure if a detailed agenda was created yet, but I would also like to request that if there is an agenda item for Isolated Web Apps that it also be on the Monday or Tuesday, not Friday as I am unable to attend on that day.

Regards

Matt

**Comment by LJWatson** [comment]
Thanks @mgiuca, everyone. Could you all give us an estimate of the time you think you'll need for your topic? If you can do this by the end of this week, we'll get the agenda posted soon.

**Comment by reillyeon** [comment]
Edited above.

**Comment by shivanigithub** [comment]
For the fenced frames session requested [above](https://github.com/WICG/admin/issues/181#issuecomment-1533496299), requested time is 1 hr (but if that's not possible since the original post says 45 mins, then that works too), thanks!
Also since I'll be presenting remotely, if possible, can this session be in an EST friendly time?

**Comment by michaelkleber** [comment]
Edited above

**Comment by csharrison** [comment]
If it isn't too late I would like to host a session on Mon-Wed on the [Attribution Reporting API](https://github.com/WICG/attribution-reporting-api). Requested time is 1hr. Discussion can highlight a few usability proposals we are considering.

**Comment by npdoty** [comment]
Is there an agenda/schedule for WICG sessions at TPAC?

**Comment by a-sully** [comment]
Apologies for the last-minute request, but I'd like to host a 1-hour session on [File System](https://github.com/WICG/file-system-access). Monday or Friday would be ideal. There are several in-progress and upcoming proposals I'd like to discuss. Thanks!

**Comment by michaelkleber** [comment]
If the WICG TPAC slot schedule is not yet set, then: PATCG is meeting Monday 14:30-16:30, and it would be great if the Protected Audience API slot could avoid conflicting.

**Comment by LJWatson** [comment]
We've posted the [WICG TPAC agenda](https://github.com/WICG/admin/wiki/TPAC-2023-agenda
). Hopefully we've found time for everything.

There may be times, notably Tuesday and part of Friday, when none of the WICG Chairs is able to attend. The agenda includes some informationon managing meetings that we'd appreciate you following if this encompasses one of your sessions. Thanks.

**Comment by csharrison** [comment]
Would it be possible to move the Attribution Reporting API meeting to Tuesday? Right now it conflicts with the PATCG meeting.

**Comment by LJWatson** [comment]
I'll have a go @csharrison, but before I do, can I confirm you'd like it on Tuesday? https://github.com/WICG/admin/issues/181#issuecomment-1699384423 mentioned Monday or Wednesday.

**Comment by csharrison** [comment]
> I'll have a go @csharrison, but before I do, can I confirm you'd like it on Tuesday? [#181 (comment)](https://github.com/WICG/admin/issues/181#issuecomment-1699384423) mentioned Monday or Wednesday.

Sorry I was confusing in my previous message, by "Mon-Wed" I was trying to be inclusive of Tuesday, so yes that works for me.

**Comment by LJWatson** [comment]
No problem @csharrison. The Attribution reporting API session is now on Monday. 

@michaelkleber not the Protected Audience API session is now on Tuesday.

**Comment by michaelkleber** [comment]
Thank you!  @LJWatson In case it helps, the [Monday](https://www.w3.org/2023/09/TPAC/schedule.html#monday) schedule shows the PATCG meeting ending at 16:30, while the Monday WICG slot runs to 18:30.  So I think the last hour-and-a-half of Monday is another window of non-conflict for me and Charlie.

**Comment by LJWatson** [comment]
Thanks @michaelkleber. Unless there are definite conflicts with the schedule as it is, I'd rather not play any more [Tetris](https://en.wikipedia.org/wiki/Tetris) with it 😊 

If there are problems though, let me know and I'll do my best to figure them out.

**Comment by mgiuca** [comment]
Hi @LJWatson . At risk of playing more Tetris, I wonder if it would be possible to move the Isolated Webapps item from Monday 14:30. (It clashes with the 14:30 discussion about i18n of manifests.) Both of these topics are directly relevant to me so I would appreciate it being moved but understand if it's hard for just me.

It could swap with Monday 17:00 Low level device API, or Tuesday 17:00 where there is nothing in this WG. I'm not attending Friday so it won't help to move it then.

I discussed with @reillyeon and he said it was OK to move. If this is too hard, no problem and thanks for your consideration.

**Comment by michaelkleber** [comment]
Oh no, wait — @LJWatson it looks like you moved the Protected Audience session to conflict with the PATCG meeting, Monday 14:30-16:30, the one block [I asked to avoid](https://github.com/WICG/admin/issues/181#issuecomment-1704493291).  (Maybe your comment above had a "Tuesday" when you meant "Monday"?)

This is a direct conflict for both me and everyone I am hoping to attract.

**Comment by LJWatson** [comment]
OK, @mgiuca and @michaelkleber hopefully that's all sorted now.

**Comment by michaelkleber** [comment]
Thank you!

**Comment by mgiuca** [comment]
Thankyou Leonie!

**Comment by marcoscaceres** [comment]
Closing! See you again next year all.
