### ISSUE TITLE
Mentioning Terms of Service and similar restrictions

### ISSUE THREAD

**Issue by stuartpb** [WICG/admin#20]
Along the same lines as [overhauling the Discourse Terms of Service](https://github.com/WICG/admin/issues/18#issuecomment-134432302), I think it's important that the README/charter mention that users are subject to the GitHub Terms of Service (when on Github), since it's not a strict subset of the Code of Conduct (for the first instance I see from [said terms of service](https://help.github.com/articles/github-terms-of-service/), I don't think the W3C has any policy about keeping out participants under the age of 13).

If there are other rules governing Community Groups (such as something that _does_ disallow participants under the age of 13), those should be mentioned in the README, too.

**Comment by marcoscaceres** [comment]
I think we are good with what we have.
