### ISSUE TITLE
Create a WICG.io landing page

### ISSUE THREAD

**Issue by yoavweiss** [WICG/admin#21]
Currently wicg.io is a placeholder. 
We should:
- Create a simple page with links to discourse, charter, gitter, etc
- Make it pretty

**Comment by AFBarstow** [comment]
How about adding a list of draft specs to the [home page](https://github.com/WICG) or create a doc that includes such a list? 

And speaking of of the drafts, it appears there are now two [ImageData conversion extensions](http://wicg.github.io/img-conversion/) and [Directory Upload](https://wicg.github.io/directory-upload/proposal.html). Is this correct; are there other drafts? 

Also, is the group going to use a consistent boilerplate for its drafts (the two drafts above use different ones) or is that up to the editor(s)?

**Comment by cwilso** [comment]
Hey, this is mostly done, and I just updated it with a fresh list of incubations, but I don't know how to get it to propage to wicg.io?

**Comment by yoavweiss** [comment]
Just updated, but IIRC correctly SW there was causing trouble when updating. @marcoscaceres were you able to look at that?

**Comment by marcoscaceres** [comment]
All is happy in wicg.io land ❤️
