### ISSUE TITLE
Discourse/wicg.io should be H2/SPDY

### ISSUE THREAD

**Issue by yoavweiss** [WICG/admin#23]

**Comment by yoavweiss** [comment]
And it is on SPDY. Waiting for the nginx ppa's to update with the latest version to move them the H2.

**Comment by marcoscaceres** [comment]
Fancy the pants!

**Comment by marcoscaceres** [comment]
This should be in the wicg.io repo. But I think we are ok with what we have right now. It's pretty fast.
