### ISSUE TITLE
Produce WICG stats

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/admin#29]
Elsewhere, @frivoal requested the following: 

> I would like to see statistics about the number of specifications started 
> in the WICG. How many of them died? How many of them lived on? How many of 
> those that lived on have graduated to a WG versus how many are still in the 
> CG? Of those that are still in the CG, how many are there because they are 
> still exploratory versus how many have turned into living standards? Of 
> those that have graduated to a WG, what was the typical level of stability? 
> Of those that have died, what were the main causes for giving up? How good 
> was the progress along TR for the specs that did make it to a WG? Are all 
> the statistics roughly the same depending on who originated the idea, or 
> are there significant differences when the originator is a browser vendor 
> vs a non-browser but experienced spec writer vs a new-comer? How do these 
> statistics compare to when early/exploratory work was still being allowed 
> in the WG? 
> 
> A well constructed study along these lines could go a long way to put to 
> rest the concerns that have been raised against mandatory incubation, or on 
> the contrary it may show that they were justified. Or maybe statistics is 
> the wrong way to go about it, but nonetheless, we need to draw lessons for 
> the life-sized experiment we've been running, and do so in a way that seems 
> fair to proponents and opponents to the idea.

**Comment by marcoscaceres** [comment]
I think it would be great to answer some of these questions. However, I don't think the WICG has been around long enough to draw a lot of meaningful conclusions, but still might be worth while and would allow us to reflect on things we need to improve, etc.

**Comment by frivoal** [comment]
Thanks for picking this up. For context, I wrote this in the [charter review of the WebPlatform WG](https://lists.w3.org/Archives/Public/public-new-work/2016Sep/0012.html).

Obviously, the WICG would need to be involved in making such a study, but I don't think it falls entirely on your shoulders. This is a much a question about how well the WICG itself works as it is a question to the WG(s) that could take new work themselves but push it to WICG about how well that is working out.

A similar, but not necessarily identical, set of question probably exists for work started in the WICG for which no existing WG would be a good host.

Even if we don't have enough data to answer properly yet, it would probably be good to start thinking about what is the right set of questions to ask, and how to get the right data (statistics, surveys...). In a way, this might even be better. If people for and against the idea of mandatory incubation can agree on the questions that would allow to put the question to rest before we know what the answer is, this could be an even more constructive exercise.

**Comment by astearns** [comment]
I would also like to see data collected on participation - how many people from how many organizations contribute to particular specifications? One of the goals of WICG is to increase inclusiveness, so we should be tracking whether we're succeeding with that.

**Comment by tabatkins** [comment]
I don't see why we can't start up this work now, even if it's too early to draw conclusions from. Less specs mean less work to get the tracking process off the ground, and less wasted time as we figure out the easiest ways to do the tracking and what info needs to be tracked.

I'm thinking a public repo here in WICG, initially listing all the WICG specs, their origins, their current status (a la the CSSWG's "work status" concept), and whether they're "done" (dead or graduated).

**Comment by marcoscaceres** [comment]
I'm on it.

**Comment by marcoscaceres** [comment]
ok, here is a start: https://github.com/WICG/admin/wiki/Stats

**Comment by marcoscaceres** [comment]
Everyone, can you please [take a look](https://github.com/WICG/admin/wiki/Stats) - we can extend this out.

Chairs, please add provenance, etc. or correct any mistakes. 

Initial observation is that Google is an innovation powerhouse 🙏. Hat's off to them pushing the web forward. 

More critically, we need to get Microsoft and Apple more involved. Also, having community specs are a little thin.

**Comment by jonathanKingston** [comment]
This highlights the exact issue I think there is with WICG. It's supposed
to be a community site yet nothing have I seen yet has graduated from an
idea or discussed and morphed into one. There are others that used the spec
template etc that also haven't had responses too. They should all be in
these stats somewhere and marked as failings. Sure some of the ideas will
never happen or are far too immature but with little to no corporate
responses I don't see that as part of how the charter should be. If a
developer builds a demo or a mockup of an issue or an idea it should be
looked into. I can think of dozens of threads that had significant value to
be worked upon or at least responded to with something like "hey this is
great, we are working on Houdini/xObserver/... Which should solve you issue
<insert demo code>. We would value your feedback on if this solves your
issue"

Sure some threads are painful too for example the 15 on can we have real
world dimensions on the screen in CSS...for those we need stock wiki
answers instead pointing at "why we can't have nice things" explainers.

Unless of course I misunderstood what WICG was and it's actually just a
lightweight standards body for big companies to push their own ideas
through?

**Comment by marcoscaceres** [comment]
> This highlights the exact issue I think there is with WICG. It's supposed
> to be a community site yet nothing have I seen yet has graduated from an
> idea or discussed and morphed into one.

That's not true. There are quite a few that started on discourse. We need to mark those clearly, obviously. 

A good number where sent to us by various WGs (e.g., web perf, device APIs, and web app sec). 

> There are others that used the spec
> template etc that also haven't had responses too. They should all be in
> these stats somewhere and marked as failings.

Sure. That's fair. This was first pass of things that actually made it as far as being given a repo. 

>  I can think of dozens of threads that had significant value to
> be worked upon or at least responded to with something like "hey this is
> great, we are working on Houdini/xObserver/... Which should solve you issue
> < insert demo code >. We would value your feedback on if this solves your
> issue"

Sure. But please remember that the Chairs are only human and are all part time volunteers. We can't possibly know everything that is going on in every single group at the W3C - or in every single discussion that is taking place. We rely on people on discourse to help each other. That was the intent.   

> Sure some threads are painful too for example the 15 on can we have real
> world dimensions on the screen in CSS...for those we need stock wiki
> answers instead pointing at "why we can't have nice things" explainers.

We will hopefully get those over time. 

> Unless of course I misunderstood what WICG was and it's actually just a
> lightweight standards body for big companies to push their own ideas
> through?

Why can't it be both? There is nothing wrong with being part of a big company (you and I both work for one).

**Comment by marcoscaceres** [comment]
I added most of the links to the relevant discourse threads. I didn't finish tho. If anyone wants to be a hero and take over, adding links... please do. 

Still need help with the status of various proposals. I think only CSS Parser is really dead?

**Comment by jonathanKingston** [comment]
To clarify Marcos and I spoke and agreed to do more for devs including
connecting developers with standardistas and to resolve more conversations
too.

My issue wasn't with companies more just developers not being heard.

**Comment by frivoal** [comment]
@marcoscaceres Thanks for starting the table. paymentRequest is listed as graduated, but [its github repo](https://github.com/WICG/historical-paymentrequest) says:

> This proposal was presented to the Web Payments Working Group but was not adopted

Which doesn't sound like graduation to me. Is the github readme statement out of date?

**Comment by marcoscaceres** [comment]
> Which doesn't sound like graduation to me. Is the github readme statement out of date?

Ah, that's a misunderstanding. That particular API shape was not the final one, but there was enough momentum in the Web community that a significant number of folks agreed that a full W3C WG should be started. Thus: it graduated to a real WG based on the incubation. 

It again shows that "the system works": because there was enough false starts and enough discussion to get everyone excited enough to migrate the work to a "real" WG. The point of the WICG is not to create fully baked APIs (that's a nice side effect, like with Event Listener Options), but to instead to have a space to informally experiment and rapidly innovate on things - or to fail fast. Web Payments saw both: it failed fast - but proved that "we totally can do this! Let's standardize for realz".

**Comment by marcoscaceres** [comment]
@jonathanKingston, we had a call today with the other Chairs. We will strive to do better to connect developers and implementers... but we need folks like yourself to help us: if you see something that looks "standards worthy" (and the Chairs or implementers missed it or don't seem to get it), then please do yell at us! :) We will then do our best to help shop it around internally to browser engineering teams to evaluate if the proposal has merit - or if it could be done in some other way, etc. 

When things slip through the cracks, it's not intentional. 

Additionally, as you suggested in our discussion, we need to totally spin up a: "Why we can't, sometimes, have nice things" in the Wiki - to help clarify why some proposals won't get uptake by implementers.

**Comment by marcoscaceres** [comment]
@frivoal, I've asked the other chairs help me populate the table. I spent a few hours yesterday, looking over the history of each proposal. The process takes a little time, so hopefully we should be able to answer most of your questions within a week or two.

**Comment by marcoscaceres** [comment]
@frivoal we put this together, which we are actively maintaining as best we can:
https://docs.google.com/spreadsheets/d/1K2EtkvKXMDk_h2goR34uMIWmw1LfPhIi-QAJHcQBP_4/edit?usp=sharing

**Comment by frivoal** [comment]
@marcoscaceres, thank you for collecting the info.

As for the place this information is hosted in, unfortunately, Google docs is not accessible from China, which makes it a sub-optimal place to host documents that are of general interest to members of the w3c.

**Comment by marcoscaceres** [comment]
Hmm, that’s unfortunate. It’s the best tool we have for this tho. If anyone from China ever wants a copy, we can export one out for them.
