### ISSUE TITLE
Write up process to transfer a repo to WICG

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/admin#30]
Steps: 

 1. Make sure they are WICG Members and have signed IPR agreement ([join](https://www.w3.org/community/wicg/)). 
 1. Invite the repo owner to the WICG - through the [people interface](https://github.com/orgs/WICG/people). Add them to the "collaborator" group. 
 1. Once they accept the invite, ask them to transfer the repo over.  
 1. Add the user back as admin, through the repository interface. 
 1. Add the repo to the [repo manager](https://labs.w3.org/hatchery/repo-manager/)

Done.

**Comment by marcoscaceres** [comment]
Ok, so just did another one... one of the things that is critical is making sure the person who has the repo is first added to the WICG as a member.

**Comment by marcoscaceres** [comment]
(they don't need to be admin, just a member)

**Comment by marcoscaceres** [comment]
Another important step is making the repo owner "admin" of the repo. So, they remain a member, but can administer the repository itself. Obvious, I know... but it's still a box that needs to be checked.

**Comment by yoavweiss** [comment]
Can we script some of that away?

**Comment by marcoscaceres** [comment]
Maybe, but let's first get it "down on paper".

**Comment by marcoscaceres** [comment]
Ok, another critical step is that the person is added to an actual team. We should use:
https://github.com/orgs/WICG/teams/collaborators

**Comment by yoavweiss** [comment]
> Another important step is making the repo owner "admin" of the repo

@marcoscaceres - Is that before or after the repo is moved over?

**Comment by jonathanKingston** [comment]
@yoavweiss before, I had to be added to a team before I could transfer ownership over.

**Comment by marcoscaceres** [comment]
After the repo has been imported, you need to go to:
https://labs.w3.org/hatchery/repo-manager/

And import the repository (so the magic files get created)

**Comment by marcoscaceres** [comment]
I can report a fairly painless experience now. But yes, automating all of the above would be super nice.

**Comment by marcoscaceres** [comment]
Collated the steps to the top of this issue.

**Comment by marcoscaceres** [comment]
Moved to wiki: https://github.com/WICG/admin/wiki/Process-to-transfer-a-repo
