### ISSUE TITLE
Update biblio.json when new repositories are created

### ISSUE THREAD

**Issue by reillyeon** [WICG/admin#34]
External projects consume biblio.json in order to create links to WICG specifications. This file should be updated when new repositories are created.

**Comment by marcoscaceres** [comment]
We might add our own:
https://github.com/tobie/specref/tree/master/refs

Change the biblio.js file can be painful, because it's so huge now. Eventually, when things migrate to the W3C, they will get automagically added to biblio.js

**Comment by reillyeon** [comment]
I don't understand this comment. https://github.com/tobie/specref/tree/master/refs/wicg.json is updated automatically by fetching https://github.com/WICG/admin/blob/gh-pages/biblio.json. This issue is about making sure that we update this file when new specifications are incubated in the WICG.

**Comment by marcoscaceres** [comment]
ha! I didn't know we even had a biblio.json for us already. I give up.

**Comment by marcoscaceres** [comment]
Thinking about this... we actually want this to be a hurdle. Minting a new citation reference for SpecRef should require some work (otherwise we risk adding potentially dead stuff to Specref).
