### ISSUE TITLE
Process to be given permissions to a github repository?

### ISSUE THREAD

**Issue by bmeck** [WICG/admin#35]
I have joined the WICG group and read https://github.com/WICG/admin/blob/gh-pages/README.md 

However, I do not see a process to get permissions administer/close issues on a github repository. I am looking at https://github.com/WICG/webpackage in particular.

**Comment by marcoscaceres** [comment]
I'll add you to the collaborators list. 

I'll also update the README.

**Comment by marcoscaceres** [comment]
done.

**Comment by marcoscaceres** [comment]
@bmeck, you should have gotten an invite via email. If not, let me know and I'll send you a link.
