### ISSUE TITLE
Which Discourse?

### ISSUE THREAD

**Issue by darobin** [WICG/admin#4]
We've mentioned using Discourse. Right now the community's instance is sitting at Specifiction, which is probably not a great location. The initial plan was to move it to webplatform.org, but this has been mired in the lack of decision as to what to do with that site.

Should we push to keep webplatform.org or should we just go ahead and put everything under wicg.io? I like the former's name better, and it comes with a large and relevant Twitter following, but right now it's not moving...

**Comment by jonathanKingston** [comment]
I personally think either is fine but I certainly think the longer the move is stalled, the more people are getting disincentivised to contribute to specifiction.

Will putting the the platform on webplatform mean that it will be hard to maintain in future?

**Comment by darobin** [comment]
The problem with WebPlatfom is that the powers-that-be have not yet reached a decision as to what to do with it. That's why all decisions are stalled there, and why the migration hasn't been proceeding even though it was announced and we actually have an instance up and running.

I'm not sure how much of this is public, so I'm being careful. @shepazu @sideshowbarker would probably be able to be explain more.

**Comment by sideshowbarker** [comment]
I think we should just go ahead and create discuss.webplatform.org or discourse.webplatform.org or whatever people currently think is best, and move on. I also don’t understand who it is that needs to make the decision to do that. But I hope we can get whoever it is to just do it.

**Comment by marcoscaceres** [comment]
So, https://discuss.webplatform.org/ is already there... @darobin, what else is needed? What didn't migrate?

**Comment by marcoscaceres** [comment]
Hmm... maybe we should centralize actually... discuss.wicg.io might be nice. Give us a fresh start and all that.

**Comment by darobin** [comment]
There are only three things needed for discuss.wpo:
1. recreate the auth token with all the auth services we use
2. check the mail configuration works
3. freeze the current Discourse and activate the new one with a redirect

None of this is time-consuming. But since I can't seem to get a decision about that in general, I'm doing other stuff. I don't disagree that it would be a good idea to have everything in the same place; I'm happy to give you the access you need to set up the same Discourse over under wicg.io and then redirect.

**Comment by marcoscaceres** [comment]
@yoavweiss, wdyt?

**Comment by tobireif** [comment]
Would using GitHub issue threads (for the web platform suggestions) be an option?

**Comment by yoavweiss** [comment]
We (read: mostly @darobin) have moved the discourse instance to http://discourse.wicg.io

@tobireif - I guess we could spin up a proposals repo that would contains new suggestions, but it would be a duplicate (in a way) of discourse.

(thinking out loud) We could have a proposed workflow of something like:
- Initial proposal & discussion on discourse
- Assuming a few people are positive about the proposal, we spin up a repo and give the main proposer the keys (or proposers spin up their own repos)
- Further detailed discussions and work happens in the repo

WDYT?

**Comment by tobireif** [comment]
I'd keep it as simple as possible - one single place for _suggestions_, eg either Discourse threads or GitHub threads.
(If the W3C then deems it sensible to create a repo for steps to be taken after the suggestion thread, that's fine with me :) I probably couldn't afford to invest additional time after a suggestion thread.)

GitHub threads (for suggestions) would be more convenient (than Discourse) because many already have a GitHub account. But since you / @darobin moved the discourse instance to http://discourse.wicg.io , that probably is the place for suggestions now, and it will probably be OK.

**Comment by marcoscaceres** [comment]
We are using http://discourse.wicg.io/

**Comment by yoavweiss** [comment]
hopefully https soon...
