### ISSUE TITLE
DevTools Protocol WICG missing

### ISSUE THREAD

**Issue by auchenberg** [WICG/admin#57]
I noticed that https://github.com/WICG/devtools-protocol are missing from the list on https://wicg.io/

What's the process for getting it added? We don't have a `gh-pages` branch yet with a formel spec or homepage.

**Comment by marcoscaceres** [comment]
Once you have a spec, we simply add it to: https://github.com/WICG/admin/blob/gh-pages/biblio.json

**Comment by auchenberg** [comment]
Great, that makes it easy.
