### ISSUE TITLE
Add as collaborator

### ISSUE THREAD

**Issue by ghost** [WICG/admin#66]
Hi there,

Please can I be added as a collaborator on GitHub?

Thanks,
Becca

**Comment by marcoscaceres** [comment]
Hi Becca, really sorry for the dalay! Which repo did you want to be a collaborator on?

**Comment by sideshowbarker** [comment]
@rebeccahughes I had the system send you an invite for https://github.com/WICG/audio-focus

**Comment by ghost** [comment]
Hi there,

Apologies but could you switch my access to @beccahughes instead? Also, please can I get access to the media session and autoplay repos too?

Thanks,
Becca

**Comment by sideshowbarker** [comment]
> Apologies but could you switch my access to @beccahughes instead? Also, please can I get access to the media session and autoplay repos too?

OK — there should now be write-access invites for all three repos waiting at @beccahughes
