### ISSUE TITLE
https://wicg.io bad link for "W3C membership"

### ISSUE THREAD

**Issue by scheib** [WICG/admin#77]
Landing page for https://wicg.io has a bad link for "W3C membership".  It currently links to 

https://www.w3.org/2004/01/pp-impl/65406/instructions
"INSTRUCTIONS FOR WEB AND MOBILE INTEREST GROUP
The Web and Mobile Interest Group is now closed."

**Comment by marcoscaceres** [comment]
@yoavweiss, could you please do a `git pull` on wicg.io ?

**Comment by yoavweiss** [comment]
Done!
