### ISSUE TITLE
w3.org/community/wicg and wicg.io need to link to other WICG pages.

### ISSUE THREAD

**Issue by scheib** [WICG/admin#80]
Problem: Web search for WICG suggests w3.org/community/wicg.  That page links to the charter, but not information on process that is documented on github.com/wicg/admin, nor the https://wicg.io page.

Similarly, https://wicg.io does not cross-link to the community group, or the github admin page.

Chore: Edit w3.org/community/wicg and https://wicg.io/ to link to each other and github.com/WICG/admin.

**Comment by travisleithead** [comment]
Woot! @cwilso [just posted](https://www.w3.org/community/wicg/2020/05/14/work-mode/) the links to Github from the community page. Our website already linked back to Github and the community page.

So, I think we're good!
