### ISSUE TITLE
Fix IPR for repositories

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/admin#81]
@dontcallmedom found a bunch of issues with our repositories around IPR etc: 
https://w3c.github.io/validate-repos/report.html

We need to go through the list above and click the buttons in the repo manager to fix things.

**Comment by travisleithead** [comment]
## Missing data in w3c.json

- [x] WICG/BackgroundSync: repo-type (not rec-track)
- [x] WICG/badging: repo-type (not rec-track)
- [x] WICG/cors-rfc1918: repo-type (not rec-track)
- [x] WICG/cq-usecases: repo-type (not rec-track)
- [x] WICG/entries-api: repo-type (not rec-track)
- [x] WICG/focus-visible: repo-type (unknown)
- [x] WICG/imageresource: repo-type (not rec-track)
- [x] WICG/indexed-db-observers: repo-type (not rec-track)
- [x] WICG/InputDeviceCapabilities: repo-type (not rec-track)
- [x] WICG/interventions: repo-type (not rec-track)
- [x] WICG/logical-sizing-properties: repo-type (not rec-track)
- [x] WICG/memory-pressure: repo-type (not rec-track)
- [x] WICG/netinfo: repo-type (not rec-track)
- [x] WICG/origin-policy: repo-type (not rec-track)
- [x] WICG/overscroll-scrollend-events: repo-type (not rec-track)
- [x] WICG/purification: repo-type (not rec-track)
- [x] WICG/ResizeObserver: repo-type (not rec-track)
- [x] WICG/scroll-animations: repo-type (not rec-track)
- [x] WICG/serial: repo-type (not rec-track)
- [x] WICG/web-share-target: repo-type (not rec-track)
- [x] WICG/webusb: repo-type (not rec-track) 

## Missing w3c.json file

- [x] WICG/admin
- [x] WICG/aom
- [x] WICG/background-fetch
- [x] WICG/canvas-color-space
- [x] WICG/change-password-url
- [x] WICG/construct-stylesheets
- [x] WICG/container-queries
- [x] WICG/controls-list
- [x] WICG/cookie-store
- [x] WICG/CSS-Parser-API
- [x] WICG/datacue
- [x] WICG/devtools-protocol
- [x] WICG/discourse-wicg-theme
- [x] WICG/display-locking
- [x] WICG/encrypted-media-encryption-scheme
- [x] WICG/event-timing
- [x] WICG/file-handling
- [x] WICG/get-installed-related-apps
- [x] WICG/hdcp-detection
- [x] WICG/import-maps
- [x] WICG/inert
- [x] WICG/keyboard-lock
- [x] WICG/keyboard-map
- [x] WICG/media-source
- [x] WICG/native-file-system
- [x] WICG/permissions-request
- [x] WICG/permissions-revoke
- [x] WICG/priority-hints
- [x] WICG/shape-detection-api
- [x] WICG/spatial-navigation
- [x] WICG/starter-kit
- [x] WICG/sw-launch
- [x] WICG/visual-viewport
- [x] WICG/web-locks
- [x] WICG/webhid
- [x] WICG/webpackage
- [x] WICG/wicg.github.io
- [x] WICG/wicg.io

## Not configured with the Repo Manager

- [x] WICG/frame-timing
- [x] WICG/kv-storage
- [x] WICG/largest-contentful-paint
- [x] WICG/page-lifecycle

## Configured with the Repo Manager, but missing the github webhook

- [x] WICG/BackgroundSync
- [x] WICG/webusb
- [x] WICG/ResizeObserver

**Comment by marcoscaceres** [comment]
Finished off the last few. Thanks @travisleithead for doing all the monotonous clicking on these! 

@WICG/chairs ... reminder for all of us to always import new repositories:
https://labs.w3.org/repo-manager/repo/import

As a reminder, we have an "IPR" column in the spreadsheet... maybe I should change that to "repo-manager" 🤔
