### ISSUE TITLE
wicg.io out of sync with active repos....

### ISSUE THREAD

**Issue by travisleithead** [WICG/admin#83]
Noted that our Chairs tracking spreadsheet (The Truth) seems out of sync with wicg.io, which is itself apparently powered by [biblio.json](https://github.com/WICG/admin/blob/gh-pages/biblio.json). Do these need to synced-up? (Should we add that as a column in the spreadsheet?

**Comment by marcoscaceres** [comment]
Yep, we need to sync em... But we need to use the sheet API to export the data.

**Comment by yoavweiss** [comment]
wicg.io should now be in sync, getting the data from GH
