### ISSUE TITLE
Process for scheduling and organizing VCs or calls?

### ISSUE THREAD

**Issue by csharrison** [WICG/admin#84]
Hey folks,
I'm new to participating in the WICG and I was wondering what the desired process is for scheduling calls among interested parties (e.g. for a topic like https://github.com/WICG/trust-token-api) and if there are canonical tools to do so.

I chatted with @yoavweiss offline who mentioned that scheduling via github issues might be a good idea, but to file an issue here to see what people think.

**Comment by yoavweiss** [comment]
@cwilso @marcoscaceres @travisleithead - WDYT? 
Is scheduling calls on an issue good enough? Do we need a W3C archived mailing list? Something else?

**Comment by marcoscaceres** [comment]
I think it's fine to just use an issue... obviously, just make sure the people you want to attend the meeting are also tagged.

**Comment by marcoscaceres** [comment]
Closing as answered.
