### ISSUE TITLE
Make it more clear that WICG drafts should use CG-DRAFT instead of ED

### ISSUE THREAD

**Issue by jyasskin** [WICG/admin#90]
Forked from discussion in https://github.com/WICG/admin/issues/79#issuecomment-584349305 and https://github.com/w3c/tr-design/issues/186#issuecomment-584413766. See also #64.

I didn't realize that the ED status was meant for WG drafts, and that editor's drafts of CG specifications should use CG-DRAFT instead. It looks like lots of other editors have the same confusion. CGs generally should find a way to educate editors on this, but the WICG is as good a place as any to start looking for ways that work.

One thought is to edit https://github.com/tabatkins/bikeshed/tree/master/bikeshed/boilerplate/wicg to add a `header-ED.include` that loudly says to use the CG-DRAFT status instead. @tabatkins, does that make sense?

What other approaches should we try?

This is also a good place to disagree if the policy @marcoscaceres suggested is wrong for some reason. :smiley:

**Comment by tabatkins** [comment]
I could do that, or just have a check in Bikeshed that if your group is WICG and your status isn't one of the WICG statuses, it throws a fatal error.

Maybe pair that with an ED boilerplate that looks terrible too, in case people ignore the error. ^_^

**Comment by jyasskin** [comment]
If Bikeshed were to actually have logic for this, I'd want it to identify all CGs to treat them uniformly, and probably ban all of the WG statuses. The ED boilerplate was the cheap idea. But maybe we can identify CG groups because they end with "cg"?

**Comment by marcoscaceres** [comment]
Something like that might work. Definitely worth investigating.

**Comment by jyasskin** [comment]
Marcos also found a [draft](https://github.com/WICG/construct-stylesheets/pull/121) that forgot to set a Group despite being in the WICG Github org. We could detect that either by having Bikeshed constrain the acceptable groups based on the [Repository](https://tabatkins.github.io/bikeshed/#metadata-repository) or by telling Github to run some lint check across the whole org.

**Comment by marcoscaceres** [comment]
> telling Github to run some lint check across the whole org.

I had no idea one could do that. Do you have a link to some docs or an example? I guess it could be as simple as find `*.bs` and then grep'ing for Group:\s+WICG or similar.

**Comment by jyasskin** [comment]
I think we could write a Github App to lint specs on each PR, and install it across the whole org. I suspect the Bikeshed patch will be easier.

**Comment by tabatkins** [comment]
Yeah, and I'm happy to write or accept such a patch.

**Comment by hober** [comment]
I'm pretty sure some recent-ish Bikeshed changes I've made take care of this, though it warns, it doesn't error. (You can always `--die-on=warning` if you want that. See tabatkins/bikeshed#1663 tabatkins/bikeshed#1684 for the relevant changes.)

Maybe this can be closed now?

**Comment by marcoscaceres** [comment]
Filed a bug on ReSpec https://github.com/w3c/respec/issues/3017 ... can follow up there.
