### ISSUE TITLE
Create repo request

### ISSUE THREAD

**Issue by beccahughes** [WICG/admin#91]
Please can we create a repo for this proposal?

https://discourse.wicg.io/t/proposal-media-feeds-api/4223

**Comment by marcoscaceres** [comment]
Thanks @beccahughes. I've asked inside Mozilla for someone to take a look. If you haven't already, it might be a good idea to also notify the Media Working Group about this proposal (or this this originate as an idea there?)? 

I'm hoping we can and indication of interest from one Apple, Mozilla, or one of streaming or news sites that they'd like to be part of the discussion as part of spinning up the repo. If you've got some folks in the community that you will be working with on it, then we are in good position to spin this up!

**Comment by beccahughes** [comment]
@mounirlamouri is aware of this work but I will send an email to Media WG to share this proposal

**Comment by travisleithead** [comment]
I had our media folks look this over, and the primary feedback was "why is a browser API needed for this when it should be done by page content". Might help to clarify that?

**Comment by beccahughes** [comment]
I'm not quite sure what you mean by "done by page content" do you have any more context?

**Comment by travisleithead** [comment]
Sorry, should have read the feedback more carefully, should be: "why is a browser API needed for this when it is typically done on the cloud for most large sites"?

In "done by page content", I was assuming a web page hosting the media would also aggregate preferences on the client (e.g., using fetch), but it makes more sense that it be done on the server given previously requested media resources (history), associated state (logged in), etc. I suppose client-side would enable cross-origin preference analysis, but how that relates to the developer is a bit mysterious to me.

**Comment by beccahughes** [comment]
Sure. We have three main reasons we want to do this on the client side:

1. The browser has the login state (in the form of cookies) for the user and can fetch recommendations using this context

2. Any site the browser can access can serve recommendations. This means that any site can add a feed and take advantage of this feature without needing to do server side integration.

3. Fetching recommendations on the client side is far better for the user in terms of privacy and some sites won't even adopt a server-to-server API because they want to be careful about where their user data goes.

**Comment by marcoscaceres** [comment]
spun up https://github.com/WICG/media-feeds-api
