### ISSUE TITLE
How does someone go about transferring a repo from WICG to another CG?

### ISSUE THREAD

**Issue by hober** [WICG/admin#93]
The current plan of record is for Private Click Measurement to move to the Privacy CG (see privacycg/proposals#1 and WICG/ad-click-attribution#32).

Before I bungle everything by clicking the Transfer button, is there anything else I need to do? How does this usually work?

cc @WICG/chairs

**Comment by marcoscaceres** [comment]
@hober, transfer using the transfer button is totally fine! That's the way to do it!

**Comment by yoavweiss** [comment]
It would be good to wait with the transfer until the situation around the Privacy CG clears and all the contributors to the current proposal can continue to contribute over there as well. 

There's also the competing [Conversion Measurement API](https://discourse.wicg.io/t/conversion-measurement-api/3580) proposal, which its TAG review [suggested](https://github.com/w3ctag/design-reviews/issues/418#issuecomment-573772095) would be good to integrate with this incubation. I don't think we want to block such collaboration opportunities from happening.

**Comment by cwilso** [comment]
Better link for Conversion Measurement API, btw: https://github.com/WICG/conversion-measurement-api.

**Comment by hober** [comment]
Hi all,

Sorry it took so long for me to get back to this.

It might be worth saying that PCM is an obvious fit for the work done in the Privacy CG. The CG was founded precisely to be a venue for this kind of work! We want to make use of all the privacy expertise and mindset in that group (more than 140 participants from over 60 organizations!) to progress the proposal. Had the Privacy CG existed at the time, we would have taken the work straight there.

[Marcos wrote](https://github.com/WICG/admin/issues/93#issuecomment-597562511):

> > @hober, transfer using the transfer button is totally fine! That's the way to do it!

Great, thanks!

[Yoav wrote](https://github.com/WICG/admin/issues/93#issuecomment-597617802):

> It would be good to wait with the transfer until the situation around the Privacy CG clears

Can you be more specific about your concern? If your concern was simply that Google had not joined the Privacy CG, I'm very happy to report that they joined the other day.

> and all the contributors to the current proposal can continue to contribute over there as well. 

The Privacy CG is open to all, just as WICG is.

> There's also the competing [Conversion Measurement API](https://discourse.wicg.io/t/conversion-measurement-api/3580) proposal, which its TAG review [suggested](https://github.com/w3ctag/design-reviews/issues/418#issuecomment-573772095) would be good to integrate with this incubation.

**[TAG hat on]**
I think this is a misunderstanding of that comment, which suggests layering the two specs. Our feedback was heard loud and clear, and layering the two specs [is the plan of record](https://github.com/WICG/ad-click-attribution/issues/26).
**[TAG hat off]**

> I don't think we want to block such collaboration opportunities from happening.

I agree! Could you tell me why you think transferring this spec would do that?

**Comment by marcoscaceres** [comment]
@yoavweiss, I think the last question there is for you. I personally don't see any issue with this moving over to the Privacy CG?

**Comment by yoavweiss** [comment]
It seems like the [issues](https://github.com/privacycg/privacycg.github.io/issues/9) with the Privacy CG's charter were since [resolved](https://github.com/privacycg/privacycg.github.io/pull/25) to make it more inclusive.

I remove my objections.

**Comment by hober** [comment]
Okay, great. Thanks everybody! The repo has been transferred: https://github.com/privacycg/private-click-measurement
