### ISSUE TITLE
SMS OTP Repo

### ISSUE THREAD

**Issue by samuelgoto** [WICG/admin#99]
Hi,

We'd like to spin off the SMS message format currently defined in `WICG/WebOTP` and in https://github.com/WebKit/explainers/tree/master/sms-one-time-code-format into its own repository with its own explainer, spec, and issue tracker.

Could you create a `WICG/sms-one-time-codes` repo and give @hober and myself write access?

Thanks!

Sam, Tess

(I assume we don't have to jump through hoops on Discourse to do this, since it's just a reorganization of some of the work that already graduated from Discourse into `WICG/WebOTP`.)

**Comment by cwilso** [comment]
In progress.

**Comment by cwilso** [comment]
Done. https://github.com/WICG/sms-one-time-codes.
